# This is development only. See convox.conf for production upstart config
agent:
  build: .
  entrypoint: /go/src/github.com/convox/agent/rerun-agent
  environment:
    - AWS_REGION
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - CLIENT_ID=dev@convox.com
    - KINESIS
    - LOG_GROUP
    - DEVELOPMENT=true
  volumes:
    - /tmp:/mnt/host_root
    - /sys/fs/cgroup:/cgroup
    - /var/run/docker.sock:/var/run/docker.sock
